name: GitHub Actions Workflow

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main   

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      playwright-tests: ${{ steps.playwright-tests.outputs.result }}

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

        #import content start
      - name: Checkout is373 repository
        uses: actions/checkout@v4
        with:
          #token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: yumis56/is373
          path: is373

      - name: Copy markdown files and images
        run: |
          cp -R is373/*.md ./blog/source/_posts/
          cp -R is373/images/* ./blog/source/images/

      - name: Commit and push changes
        run: |
          cd blog
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git pull origin main
          
          git add .
          git commit -m "Update md and images from is373 to is373-project" || echo "No changes to commit"
          git push origin main
         #import content end

    #hexo start
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./blog
        run: |
            npm install
            npm ci

      - name: Generate Hexo site
        working-directory: ./blog
        run: |
            npx hexo clean
            npx hexo generate
    
      - name: Start Hexo server
        working-directory: ./blog
        run: |
          npx hexo server &
          echo $! > hexo.pid
          sleep 5  # Give the server a moment to start
          echo "Hexo server started"
      #hexo end    besides closing server after playwright

      #playwright start
      - name: Checkout Playwright test repository
        uses: actions/checkout@v4
        with:
          repository: yumis56/is373-devops
          path: is373-devops

      - name: Build Docker image for Playwright tests
        working-directory: is373-devops
        run: |
          docker build -t playwright-tests .
      
      - name: Run Playwright tests in Docker
        run: |
          # This one is functioning, but I want to set conditionals
          #docker run --rm playwright-tests > playwright-results.txt || true

          RESULT_FILE="../is373-devops/test-results/playwright-results.txt"


          if docker run --rm -v ../is373-devops/test-results:/app/test-results playwright-tests > "$RESULT_FILE"; then
            echo "playwright-tests=true" >> $GITHUB_ENV
            echo "SUCCESS: Check report in is373-devops/test-results/playwright-results.txt"
          else
            echo "playwright-tests=false" >> $GITHUB_ENV
            echo "FAILURE: Check report in is373-devops/test-results/playwright-results.txt"
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: playwright-results.txt
      #playwright end

     
      - name: Stop Hexo server
        working-directory: ./blog
        if: always()
        run: |
          kill `cat hexo.pid`
      

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    #if: github.event_name == 'push'
    if: success() && needs.build-and-test.outputs.playwright-tests == 'true'

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./blog
        run: |
            npm install
            npm install hexo-theme-landscape
            npm ci

      - name: Generate Hexo site
        working-directory: ./blog
        run: |
            npx hexo clean
            npx hexo generate
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/public  # Hexo outputs the generated files to the 'public' directory
          publish_branch: hosted-pages
          #publish_repo: yumis56/is373-project
