name: GitHub Actions Workflow

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main   

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      playwright-tests: ${{ steps.playwright-tests.outputs.result }}

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

        #import content start
      - name: Checkout is373 repository
        uses: actions/checkout@v4
        with:
          #token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: yumis56/is373
          path: is373

      - name: Copy markdown files and images
        run: |
          cp -R is373/*.md ./blog/source/_posts/
          cp -R is373/images/* ./blog/source/images/

      - name: Commit and push changes
        run: |
          cd blog
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git pull origin main
          
          git add .
          git commit -m "Update md and images from is373 to is373-project" || echo "No changes to commit"
          git push origin main
         #import content end

    #hexo start
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./blog
        run: |
            npm install
            npm ci

      - name: Generate Hexo site
        working-directory: ./blog
        run: |
            npx hexo clean
            npx hexo generate
    
      - name: Start Hexo server
        working-directory: ./blog
        run: |
          npx hexo server &
          echo $! > hexo.pid
          sleep 5  # Give the server a moment to start
          echo "Hexo server started"
      #hexo end    besides closing server after playwright

      #playwright start
      - name: Checkout Playwright test repository
        uses: actions/checkout@v4
        with:
          repository: yumis56/is373-devops
          path: is373-devops

      - name: Build Docker image for Playwright tests
        working-directory: is373-devops
        run: |
          docker build -t playwright-tests .
      
      - name: Run Playwright tests in Docker
        id: playwright-tests
        run: |
          # This one is functioning, but I want to set conditionals
          docker run --rm playwright-tests > playwright-results.txt || true
          
          #docker run --rm playwright-tests > playwright-results.txt
          #echo "result=$(grep -c 'fail' playwright-results.txt)" >> $GITHUB_ENV
          #echo "Playwright tests result: ${{ env.result }}"


      # TODO: figure out how to save from Docker    
      #- name: Save Test Results
      #  run: |
      #    cd is373-devops
      #    
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    
      #    git pull origin main
      #    
      #    git add playwright-results.txt
      #    git commit -m "Add test results"
      #    git push origin main

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        with:
            name: playwright-results
            path: playwright-results.txt
            if-no-files-found: warn
            compression-level: 6
            overwrite: false
            include-hidden-files: false

      - name: Save artifact URL
        run: |
          echo "ARTIFACT_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload-artifact.outputs.artifact_id }}" >> $GITHUB_ENV

      #playwright end
      - name: Print artifact URL
        run: |
          echo "Artifact URL: ${{ env.ARTIFACT_URL }}"

      - name: Download test results
        run: |
          cd is373-devops
          mkdir -p is373-devops/test-results
          curl -L -o is373-devops/test-results/playwright-results.txt ${{ env.ARTIFACT_URL }}

      - name: Commit and push changes
        run: |
          cd is373-devops
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git pull origin main
          
          git add is373-devops/test-results/playwright-results.txt
          git commit -m "Add Playwright test results"
          git push origin main
          #git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/yumis56/is373-devops.git main

     
      - name: Stop Hexo server
        working-directory: ./blog
        if: always()
        run: |
          kill `cat hexo.pid`
      

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    #if: success() && needs.build-and-test.outputs.playwright-tests == '0'

    #if: success() && needs.build-and-test.outputs.playwright-tests == 'true'

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./blog
        run: |
            npm install
            npm install hexo-theme-landscape
            npm ci

      - name: Generate Hexo site
        working-directory: ./blog
        run: |
            npx hexo clean
            npx hexo generate
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/public  # Hexo outputs the generated files to the 'public' directory
          publish_branch: hosted-pages
          #publish_repo: yumis56/is373-project
