name: GitHub Actions Workflow

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main   

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v4
        
      - name: Checkout is373 repository
        uses: actions/checkout@v4
        with:
          #token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: yumis56/is373
          path: is373

      - name: Copy markdown files and images
        run: |
          cp -R is373/*.md ./blog/source/_posts/
          cp -R is373/images/* ./blog/source/images/

      - name: Commit and push changes
        run: |
          cd blog
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git pull origin main
          
          git add .
          git commit -m "Update md and images from is373 to is373-project" || echo "No changes to commit"
          git push origin main
         
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./blog
        run: |
            npm install
            npm ci

      - name: Generate Hexo site
        working-directory: ./blog
        run: |
            npx hexo clean
            npx hexo generate

    
      - name: Start Hexo server
        working-directory: ./blog
        run: |
          npx hexo server &
          echo $! > hexo.pid
          sleep 5  # Give the server a moment to start
          echo "Hexo server started"
  

    
      - name: Checkout Playwright test repository
        uses: actions/checkout@v4
        with:
          repository: yumis56/is373-devops
          path: is373-devops
        #testing stuff out  
      - name: Build Docker image for Playwright tests
        working-directory: is373-devops
        run: |
          docker build -t playwright-tests .
      
      - name: Run Playwright tests in Docker
        run: |
          docker run --rm playwright-tests > playwright-results.txt || true
    
   
      #- name: Install Playwright dependencies
      #  working-directory: is373-devops
      #  run: |
      #    npx playwright install-deps
      #    npm ci
        
      #- name: Install Playwright browsers
        #working-directory: is373-devops
        #run: npx playwright install

      #- name: Run Playwright tests
        #working-directory: is373-devops
        #id: playwright-tests
        #run: npx playwright test --config=playwright.config.ts --reporter=list > playwright-results.txt || true
      #testing end

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: playwright-results.txt
     
      - name: Stop Hexo server
        working-directory: ./blog
        if: always()
        run: |
          kill `cat hexo.pid`


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    #if: github.event_name == 'push'
    if: success() 

    steps:
      - name: Checkout Hexo repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./blog
        run: |
            npm install
            npm install hexo-theme-landscape
            npm ci

      - name: Generate Hexo site
        working-directory: ./blog
        run: |
            npx hexo clean
            npx hexo generate
        
      #- name: List contents of publish directory
      #  run: ls -la ./blog/public 
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/public  # Hexo outputs the generated files to the 'public' directory
          publish_branch: hosted-pages
          #publish_repo: yumis56/is373-project
