name: Deploy Test Hexo

on:
  push:
    branches: [ main, master ]
  pull_request:
    #branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}/hexo-site:${{ github.sha }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public


    - name: Trigger tests in is373-devops
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: yumis56/is373-devops
        event-type: hexo-site-updated
        client-payload: '{"sha": "${{ github.sha }}", "ref": "${{ github.ref }}"}'
